development: &default
  adapter: postgresql
  database: zaqueu_development
  username: postgres
  password: root
  encoding: utf8
  host: localhost

test:
  <<: *default
  database: zaqueu_test

# production:
#   <<: *default
#   database: zaqueu_production
